language: python
# Run in a container
dist: trusty
sudo: required
python:
    - "3.5"
    - "3.6"
#Command to install dependencies
git:
    depth: 1
install: 
    - pip install --quiet -r requirements.txt
    - pip install .
script: pytest 
